# Generated by Django 2.0.7 on 2018-07-25 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('completion_date', models.DateTimeField()),
                ('priority', models.CharField(choices=[('high', 'High Priority'), ('normal', 'Normal Priority'), ('low', 'Low priority')], max_length=100)),
                ('is_completed', models.BooleanField(default=False)),
            ],
        ),
    ]
